default_stages: [commit, push]
default_language_version:
  python: python3
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
        exclude: migrations/
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      args: [
        --line-length=120,
        --target-version=py311
      ]
      exclude: migrations/
      types: ['python']
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - --quiet
          - -s
          - B311,B105,B113
        exclude: tests/
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
        exclude: migrations/
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
