version: "3"

services:
  app:
    restart: always
    build: .
    container_name: app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./:/src/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://backend:backend@db:5432/backend
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/15/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend

volumes:
  postgres_data: